name: Get Minecraft Translations (Datapacks)

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  get_items:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create translations directory
      run: mkdir -p datapack_translations

    - name: Run items script
      run: |
        cat << EOT > get_items.py
        import requests
        import zipfile
        import io
        
        versions_url = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
        versions = requests.get(versions_url).json()
        latest_version = versions["versions"][0]
        version_url = latest_version["url"]
        version = requests.get(version_url).json()
        client_url = version["downloads"]["client"]["url"]
        client = requests.get(client_url).content
        jar = zipfile.ZipFile(io.BytesIO(client))
        file_path = "assets/minecraft/lang/en_us.json"
        en_us_json = jar.read(file_path)
        dataPack_keys = [key for key in en_us_json if key.startswith(b"dataPack.")]
        with open("datapack_translations/en_us.json", "wb") as f:
            f.write(en_us_json)

        EOT
        python get_items.py

    - name: Commit and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add datapack_translations/
        git commit -m "Update translations data" -a || echo "No changes to commit"
        git push https://${PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
