name: Get Minecraft Items

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  get_items:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install Pillow

    - name: Create items directory
      run: mkdir -p items

    - name: Run items script
      run: |
        cat << EOT > get_items.py
        from concurrent.futures import ThreadPoolExecutor, as_completed
        from io import BytesIO
        import json
        from math import sqrt
        import math
        import time
        import requests
        from bs4 import BeautifulSoup
        from PIL import Image
        
        img_cache = {}
        
        def get_data(row):
            tds = row.find_all("td")
            image_url = tds[0].find("img")
            if image_url.get("data-src") is not None:
                image_url = image_url["data-src"]
            else:
                image_url = image_url["src"]
            mc_id = tds[1].text
            name = tds[2].text.strip().replace("\\n", "")
            return {
                "image_url": image_url,
                "mc_id": mc_id,
                "name": name
            }
        
        
        def get_blocks():
            print("Getting blocks")
            url = "https://minecraft.fandom.com/api.php?action=parse&format=json&prop=text%7Cmodules%7Cjsconfigvars&title=Java_Edition_data_values&text=%7B%7B%3AJava%20Edition%20data%20values%2FBlocks%7D%7D"
            response = requests.get(url)
            data = response.json()
            html = data["parse"]["text"]["*"]
            soup = BeautifulSoup(html, "html.parser")
            print("Got soup")
            table = soup.find("table", attrs={"data-description": "Block IDs"})
            blocks = []
            for row in table.find_all("tr")[1:]:
                block_data = get_data(row)
                block_data["type"] = "block"
                blocks.append(block_data)
                print(f"Got block {block_data['name']}")
            return blocks
        
        def get_items():
            print("Getting items")
            url = "https://minecraft.fandom.com/api.php?action=parse&format=json&prop=text%7Cmodules%7Cjsconfigvars&title=Java_Edition_data_values&text=%7B%7B%3AJava%20Edition%20data%20values%2FItems%7D%7D"
            response = requests.get(url)
            data = response.json()
            html = data["parse"]["text"]["*"]
            soup = BeautifulSoup(html, "html.parser")
            print("Got soup")
            table = soup.find("table", attrs={"data-description": "Item IDs"})
            items = []
            for row in table.find_all("tr")[1:]:
                item_data = {}
                td1 = row.find_all("td")[0]
                item_data["name"] = td1.text.strip()
                td2 = row.find_all("td")[1]
                item_data["mc_id"] = td2.text.strip()
                style_data = td1.find("span")["style"]
                start = style_data.find("url(") + len("url(")
                end = style_data.find(")")
                item_data["image_url"] = style_data[start:end]
                item_data["positions"] = {
                    "x": 0,
                    "y": 0
                }
                start = style_data.find("background-position:") + len("background-position:")
                end = style_data.find("px")    
                item_data["positions"]["x"] = int(style_data[start:end])
                start = end + len("px")
                end = style_data.find("px", start)
                item_data["positions"]["y"] = int(style_data[start:end])
                item_data["type"] = "item"
                items.append(item_data)
                print(f"Got item {item_data['name']}")
        
            return items
        
        def get_image_PIL(item):
            if item.get("positions") is None:
                if item["image_url"] not in img_cache:
                    res = requests.get(item["image_url"])
                    im = Image.open(BytesIO(res.content))
                    im.thumbnail((32, 32))
                    img_cache[item["image_url"]] = im
                return img_cache[item["image_url"]]
            else:
                if item["image_url"] not in img_cache:
                    res = requests.get(item["image_url"])
                    im = Image.open(BytesIO(res.content))
                    img_cache[item["image_url"]] = im
                
                pil_img = img_cache[item["image_url"]].copy()
                x = -item["positions"]["x"]
                y = -item["positions"]["y"]
                width = height = 16
                pil_img = pil_img.crop((x, y, x + width, y + height)).resize((32, 32))
                
                return pil_img
        
        def process_block(item, i, width):
            pil_image = get_image_PIL(item)
            x = (i % (width // 32)) * 32
            y = (i // (width // 32)) * 32
            print(f"Processed block {item['name']}")
            return {
                "image": pil_image,
                "position": (x, y),
                "data": {
                    "name": item["name"],
                    "id": item.get("mc_id", ""),
                    "type": item["type"],
                    "offsetX": x,
                    "offsetY": y
                }
            }
        
        def process_item(item, i, width):
            pil_image = get_image_PIL(item)
            x = (i % (width // 32)) * 32
            y = (i // (width // 32)) * 32
            print(f"Processed item {item['name']}")
            return {
                "image": pil_image,
                "position": (x, y),
                "data": {
                    "name": item["name"],
                    "id": item.get("mc_id", ""),
                    "type": item["type"],
                    "offsetX": x,
                    "offsetY": y
                }
            }
        
        def generate_data(block_data, item_data):
            full_data = block_data + item_data
            cells = len(full_data)
            width = int(sqrt(cells)) * 32
            height = math.ceil(cells / (width // 32)) * 32
            atlas = Image.new("RGBA", (width, height))
            processed_data = []
        
            # Process blocks using multithreading
            with ThreadPoolExecutor(max_workers=20) as executor:
                block_futures = [executor.submit(process_block, item, i, width) for i, item in enumerate(block_data)]
                
                for future in as_completed(block_futures):
                    result = future.result()
                    atlas.paste(result["image"], result["position"])
                    processed_data.append(result["data"])
        
            # Process items single-threaded
            for i, item in enumerate(item_data, start=len(block_data)):
                result = process_item(item, i, width)
                atlas.paste(result["image"], result["position"])
                processed_data.append(result["data"])
        
            atlas.save("items/atlas.png")
            with open("items/atlas_metadata.json", "w") as f:
                json.dump(processed_data, f, indent=4)
        
        start = time.time()
        block_data = get_blocks()
        item_data = get_items()
        print(f"Got {len(block_data)} blocks and {len(item_data)} items, generating data")
        print(f"Time taken: {time.time() - start}s")
        generate_data(block_data, item_data)
        print(f"Total time taken: {time.time() - start}s")
        EOT
        python get_items.py

    - name: Commit and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add items/
        git commit -m "Update items data" -a || echo "No changes to commit"
        git push https://${PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
